name: Write cards for README

on:
  schedule:
    - cron: "0 0 3 6 *" # Runs annually on June 3
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Fetch GitHub Stats
        run: curl -f -L -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=radical" -o profile/stats.svg

      - name: Fetch Top Languages
        run: curl -f -L -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&layout=compact&theme=radical" -o profile/top-langs.svg

      - name: Commit cards
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "build: Update README cards using public API" || exit 0
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push
